[package]
name = "buildchain"
version = "0.4.5"
authors = ["Jeremy Soller <jackpot51@gmail.com>"]
description = "Software for creating and managing a distributed and reproducible chain of builds"
documentation = "https://docs.rs/buildchain"
repository = "https://github.com/system76/buildchain"
readme = "README.md"
license = "GPL-3.0"

[lib]
name = "buildchain"
path = "src/lib.rs"

[[bin]]
name = "buildchain"
path = "src/main.rs"
doc = false

[dependencies]
base32 = "0.3"
clap = "=2.26.0"
lxd = "0.1.7"
plain = "0.2"
rand = "0.3"
reqwest = "0.9.8"
sodiumoxide = "0.0.16"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
sha2 = "0.6"
tempdir = "0.3"
